server:
  port: 6789
spring:
  application:
    name: cloud-api-sample
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.12.31.25:3306/cloud_sample?useSSL=false&allowPublicKeyRetrieval=true
      username: studio-app
      password: 3Ws6_0kQ2_2n8O
      initial-size: 10
      min-idle: 10
      max-active: 20
      max-wait: 60000

  redis:
    cluster:
      nodes: 10.12.31.27:6379,10.12.31.28:6379,10.12.31.29:6379,10.12.31.27:6380,10.12.31.28:6380,10.12.31.29:6380
    database: 0
    password: OneNET_5.0.8_Test
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB

jwt:
  issuer: DJI
  subject: CloudApiSample
  secret: CloudApiSample
  age: 86400

mqtt:
  protocol: tcp
  host: 172.19.19.152
  port: 1883
  username: admin
  password: public
  client-id: dj-test
  # Topics that need to be subscribed when initially connecting to mqtt, multiple topics are divided by ",".
  inbound-topic: sys/product/+/status,thing/product/+/requests

url:
  manage:
    prefix: /manage
    version: /api/v1
  map:
    prefix: /map
    version: /api/v1
  media:
    prefix: /media
    version: /api/v1
  wayline:
    prefix: /wayline
    version: /api/v1
  storage:
    prefix: /storage
    version: /api/v1
  control:
    prefix: /control
    version: /api/v1

# Tutorial: https://help.aliyun.com/document_detail/100624.htm?spm=a2c4g.11186623.0.0.74075e34eIhK7T#concept-xzh-nzk-2gb
oss:
  enable: true
  provider: ali # @see com.dji.sample.component.OssConfiguration.model.enums.OssTypeEnum
  endpoint: https://oss-cn-hangzhou.aliyuncs.com
  access-key: Please enter your access key.
  secret-key: Please enter your secret key.
  expire: 3600
  region: Please enter your oss region. # cn-hangzhou
  role-session-name: cloudApi
  role-arn: Please enter your role arn. # acs:ram::123456789:role/stsrole
  bucket: Please enter your bucket name.
  object-dir-prefix: Please enter a folder name.

#oss:
#  enable: true
#  provider: aws
#  endpoint: https://s3.us-east-1.amazonaws.com
#  access-key:
#  secret-key:
#  expire: 3600
#  region: us-east-1
#  role-session-name: cloudApi
#  role-arn:
#  bucket: cloudapi-bucket
#  object-dir-prefix: wayline

#oss:
#  enable: true
#  provider: minio
#  endpoint: http://192.168.1.1:9000
#  access-key: minioadmin
#  secret-key: minioadmin
#  bucket: cloud-bucket
#  expire: 3600
#  region: us-east-1
#  object-dir-prefix: wayline

logging:
  level:
    com.dji.sample: debug
  file:
    name: logs/cloud-api-sample.log

ntp:
  server:
    host: Google.mzr.me